#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE coder;
    GRANT ALL PRIVILEGES ON DATABASE coder TO seam;

    CREATE DATABASE hydra;
    GRANT ALL PRIVILEGES ON DATABASE hydra TO seam;

    CREATE DATABASE kratos;
    GRANT ALL PRIVILEGES ON DATABASE kratos TO seam;
EOSQL
